'use strict';
(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='hundred-problems-favorites-v1';let data=[],visible=[],favorites=new Set(),selected=new Set(),toastTimer,lastOpened=null,returnFocus=null;
const filters=['category','audience','scope','feasibility'];if(window.matchMedia?.('(max-width:640px)').matches)$('#advancedFilters').open=false;
function notice(text){$('#storageNotice').hidden=false;$('#storageNotice').textContent=text}
function loadFavorites(){try{const raw=localStorage.getItem(key);if(raw!==null){const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw Error('format');favorites=new Set(parsed.filter(x=>Number.isInteger(x)&&data.some(p=>p.id===x)));}}catch{notice('無法讀取原有收藏。這次仍可收藏；若瀏覽器不允許儲存，重新整理後不會保留。')}}
function saveFavorites(){try{localStorage.setItem(key,JSON.stringify([...favorites]));}catch{notice('瀏覽器目前不允許儲存。收藏只會保留在這次頁面，重新整理後會消失。')}}
function toast(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',2500)}
function sourceLink(s){let url;try{url=new URL(s.url);if(url.protocol!=='https:')return esc(s.title);}catch{return esc(s.title)}return `<a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`}
function tags(p){return `<span class="tag ${p.feasibility==='容易'?'':'medium'}">${esc(p.feasibility)}</span><span class="tag neutral">${esc(p.effort)}</span><span class="tag neutral">${esc(p.scope)}</span>`}
function card(p){return `<article class="card" data-id="${p.id}"><div class="card-head"><span class="number">${String(p.id).padStart(3,'0')}</span><span>${esc(p.category)}</span></div><h3><button data-open="${p.id}">${esc(p.title)}</button></h3><p>${esc(p.problem)}</p><p class="person">對象 · ${esc(p.audience)}</p><div class="tags">${tags(p)}</div><div class="card-bottom"><span class="card-source">${p.sources.length} 個來源</span><div><button data-favorite="${p.id}" aria-pressed="${favorites.has(p.id)}" aria-label="${favorites.has(p.id)?'取消收藏':'收藏'}：${esc(p.title)}">${favorites.has(p.id)?'★ 已收藏':'☆ 收藏'}</button> <button data-compare="${p.id}" aria-pressed="${selected.has(p.id)}" aria-label="${selected.has(p.id)?'移除比較':'加入比較'}：${esc(p.title)}">${selected.has(p.id)?'✓ 比較':'＋ 比較'}</button></div></div></article>`}
function render(){const q=$('#search').value.trim().toLocaleLowerCase();visible=data.filter(p=>(!q||[p.title,p.problem,p.audience,p.evidence,p.existing,p.gap,p.mvp,p.category,...p.sources.map(s=>s.publisher)].join(' ').toLocaleLowerCase().includes(q))&&(!$('#category').value||p.category===$('#category').value)&&(!$('#audience').value||p.audienceType===$('#audience').value)&&(!$('#scope').value||p.scope===$('#scope').value)&&(!$('#feasibility').value||p.feasibility===$('#feasibility').value)&&(!$('#favoritesOnly').checked||favorites.has(p.id)));
const sort=$('#sort').value;if(sort==='easy'){const rank={'容易':0,'中等':1,'需要合作':2};visible.sort((a,b)=>rank[a.feasibility]-rank[b.feasibility]||a.id-b.id)}else if(sort==='title')visible.sort((a,b)=>a.title.localeCompare(b.title,'zh-Hant'));else visible.sort((a,b)=>a.id-b.id);
$('#results').innerHTML=visible.map(card).join('');$('#count').textContent=`${visible.length} / ${data.length} 個問題`;$('#favCount').textContent=favorites.size;$('#empty').hidden=visible.length!==0;$('#compareBar').hidden=selected.size===0;$('#compareCount').textContent=`已選 ${selected.size} / 3 項`;$('#showCompare').disabled=selected.size<2;$('#download').disabled=visible.length===0;$('#downloadCsv').disabled=visible.length===0;}
function reset(){for(const id of filters)$('#'+id).value='';$('#search').value='';$('#favoritesOnly').checked=false;$('#sort').value='id';render()}
function section(title,text,inferred=false,cls=''){return `<section class="detail-section ${cls}">${inferred?'<span class="inferred-label">研究者構想 · 尚未驗證</span>':''}<h3>${esc(title)}</h3><p>${esc(text)}</p></section>`}
function sources(p){return `<ol class="sources">${p.sources.map(s=>`<li>${sourceLink(s)}<small>${esc(s.publisher)} · 發布：${esc(s.published)}<br>查核：${esc(s.checked)}</small></li>`).join('')}</ol>`}
function renderDetail(p){$('#detailNumber').textContent=`問題 ${String(p.id).padStart(3,'0')} / 100`;$('#detailBody').innerHTML=`<div class="detail-meta"><span class="tag neutral">${esc(p.category)}</span>${tags(p)}</div><h2 id="detailTitle">${esc(p.title)}</h2><p>${esc(p.problem)}</p><p class="small">受影響對象：${esc(p.audience)}</p>${section('觀察與證據',p.evidence,false,'observed')}${section('已有解法',p.existing)}${section('可能仍有的缺口',p.gap,true)}${section('最小原型',p.mvp,true)}${section('先做這個小型驗證',p.test,true)}${section('為什麼這樣評估可行性',p.whyFeasibility,true)}${section('限制與使用界線',p.caveat)}<section class="detail-section"><h3>來源與日期</h3><p class="small">發布日期不等於查核日期；外連將開新分頁。</p>${sources(p)}</section><div class="detail-section"><button data-favorite="${p.id}" aria-pressed="${favorites.has(p.id)}">${favorites.has(p.id)?'★ 已收藏':'☆ 收藏這個問題'}</button> <button class="outline" data-compare="${p.id}" aria-pressed="${selected.has(p.id)}">${selected.has(p.id)?'移除比較':'加入比較'}</button></div>`;$('#detail').scrollTop=0;}
function syncDetail(){const match=location.hash.match(/^#problem-(\d+)$/);const p=match&&data.find(p=>p.id===Number(match[1]));if(p){lastOpened=p.id;renderDetail(p);if(!$('#detail').open)$('#detail').showModal();document.title=`${p.title}｜100 個值得探索的問題`;}else{if($('#detail').open){$('#detail').close();const target=returnFocus?.isConnected?returnFocus:$(`[data-open="${lastOpened}"]`);target?.focus();}document.title='100 個值得探索的問題｜問題研究所';if(match)toast('找不到這個問題編號。');}}
function openDetail(id){lastOpened=id;if(location.hash===`#problem-${id}`){syncDetail();return;}returnFocus=document.activeElement;history.pushState({problemNavigation:true},'',`#problem-${id}`);syncDetail()}
function closeDetail(){if(history.state?.problemNavigation)history.back();else{history.replaceState(null,'',location.pathname+location.search);syncDetail();}}
function act(event){const opener=event.target.closest('[data-open]');if(opener){openDetail(Number(opener.dataset.open));return;}const fav=event.target.closest('[data-favorite]');if(fav){const id=Number(fav.dataset.favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();render();if($('#detail').open){const scroll=$('#detail').scrollTop;renderDetail(data.find(p=>p.id===id));$('#detail').scrollTop=scroll;$('#detail [data-favorite]')?.focus();}else $(`[data-favorite="${id}"]`)?.focus();return;}
const el=event.target.closest('[data-compare]');if(el){const id=Number(el.dataset.compare);if(selected.has(id))selected.delete(id);else if(selected.size<3)selected.add(id);else{toast('最多比較 3 項，請先移除其中一項。');return;}render();if($('#detail').open){const scroll=$('#detail').scrollTop;renderDetail(data.find(p=>p.id===id));$('#detail').scrollTop=scroll;$('#detail [data-compare]')?.focus();}else $(`[data-compare="${id}"]`)?.focus();}}
function compare(){const items=data.filter(p=>selected.has(p.id));$('#compareGrid').innerHTML=items.map(p=>`<article><span class="number">${String(p.id).padStart(3,'0')}</span><h3>${esc(p.title)}</h3><div class="tags">${tags(p)}</div>${[['對象',p.audience],['問題情境',p.problem],['證據摘要',p.evidence],['已有解法',p.existing],['缺口假設（推論）',p.gap],['原型構想（推論）',p.mvp],['小型驗證（擬議）',p.test],['可行性判斷（主觀）',p.whyFeasibility],['限制',p.caveat]].map(([k,v])=>`<h4>${esc(k)}</h4><p>${esc(v)}</p>`).join('')}<h4>來源</h4>${sources(p)}</article>`).join('');$('#compareDialog').showModal();}
function download(type){let content,mime,name;if(type==='json'){content=JSON.stringify({checked:'2026-10-05',count:visible.length,note:'觀察與研究者構想分列；不是市場、收益或專業建議。',problems:visible},null,2);mime='application/json;charset=utf-8';name='problems.json';}else{const cols=[['id','編號'],['title','問題'],['category','領域'],['audience','對象'],['scope','範圍'],['problem','情境'],['evidence','觀察證據'],['existing','已有解法'],['gap','缺口假設'],['mvp','原型構想'],['test','擬議測試'],['feasibility','主觀可行性'],['effort','原型工期估計'],['whyFeasibility','判斷依據'],['caveat','限制'],['sources','來源與日期']];const cell=s=>'"'+String(s).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';content='\ufeff'+[cols.map(c=>cell(c[1])).join(','),...visible.map(p=>cols.map(([k])=>cell(k==='sources'?p.sources.map(s=>`${s.publisher} | ${s.title} | ${s.url} | 發布 ${s.published} | 查核 ${s.checked}`).join('\n'):p[k])).join(','))].join('\r\n');mime='text/csv;charset=utf-8';name='problems.csv';}const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=`hundred-${visible.length}-${name}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已準備 ${visible.length} 筆下載`);}
$('#results').addEventListener('click',act);$('#detailBody').addEventListener('click',act);$('#search').addEventListener('input',render);for(const id of [...filters,'sort','favoritesOnly'])$('#'+id).addEventListener('change',render);$('#reset').onclick=reset;$('#emptyReset').onclick=reset;$('#closeDetail').onclick=closeDetail;$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail()});window.addEventListener('popstate',syncDetail);window.addEventListener('hashchange',syncDetail);$('#showCompare').onclick=compare;$('#clearCompare').onclick=()=>{selected.clear();render()};$('#closeCompare').onclick=()=>$('#compareDialog').close();$('#methodBtn').onclick=()=>$('#methodDialog').showModal();$('#closeMethod').onclick=()=>$('#methodDialog').close();$('#download').onclick=()=>download('json');$('#downloadCsv').onclick=()=>download('csv');
fetch('data/problems.json').then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(items=>{if(!Array.isArray(items)||items.length!==100||new Set(items.map(p=>p.id)).size!==100)throw Error('invalid');data=items;loadFavorites();for(const [id,field]of [['category','category'],['audience','audienceType'],['scope','scope'],['feasibility','feasibility']]){for(const value of new Set(data.map(p=>p[field]))){const option=document.createElement('option');option.value=value;option.textContent=value;$('#'+id).append(option)}}render();syncDetail();}).catch(()=>{$('#count').textContent='研究資料暫時無法載入';$('#results').innerHTML='<div class="notice">請重新整理頁面再試。也可以從上方「公開資料與程式」取得資料；不會顯示不完整的 100 題清單。</div>';$('#download').disabled=true;$('#downloadCsv').disabled=true;});
})();
