const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');const html=fs.readFileSync('index.html','utf8'),js=fs.readFileSync('app.js','utf8'),data=JSON.parse(fs.readFileSync('data/problems.json','utf8'));const delay=()=>new Promise(r=>setTimeout(r,40));
async function setup({hash='',stored=null,blocked=false,fail=false}={}){const dom=new JSDOM(html,{url:'https://example.org/explorer/'+hash,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async()=>({ok:!fail,json:async()=>data});w.Blob=class{constructor(parts){this.parts=parts}};w.URL.createObjectURL=b=>{w.output=b.parts.join('');return 'blob:test'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){w.fileName=this.download};if(stored!==null)w.localStorage.setItem('hundred-problems-favorites-v1',stored);if(blocked)Object.defineProperty(w,'localStorage',{get(){throw new Error('blocked')}});w.eval(js);await delay();return dom;}
(async()=>{let dom=await setup(),w=dom.window,d=w.document;const pick=(id,v)=>{d.querySelector(id).value=v;d.querySelector(id).dispatchEvent(new w.Event('change'))};const cards=()=>d.querySelectorAll('.card').length;
assert.equal(cards(),100);pick('#sort','easy');const rank={'容易':0,'中等':1,'需要合作':2},order=[...d.querySelectorAll('.card')].map(el=>data.find(p=>p.id===Number(el.dataset.id)).feasibility);assert.ok(order.every((v,i)=>i===0||rank[order[i-1]]<=rank[v]));pick('#sort','title');assert.equal(d.querySelector('.card h3').textContent,[...data].sort((a,b)=>a.title.localeCompare(b.title,'zh-Hant'))[0].title);pick('#sort','id');pick('#category',data[0].category);assert.equal(cards(),data.filter(p=>p.category===data[0].category).length);pick('#audience',data[0].audienceType);pick('#scope',data[0].scope);pick('#feasibility',data[0].feasibility);assert.ok(cards()>0);d.querySelector('#reset').click();assert.equal(cards(),100);
d.querySelector('#search').value=data[0].title;d.querySelector('#search').dispatchEvent(new w.Event('input'));assert.equal(cards(),1);d.querySelector('#download').click();assert.equal(JSON.parse(w.output).count,1);assert.equal(JSON.parse(w.output).problems[0].id,1);d.querySelector('#downloadCsv').click();assert.match(w.output,/來源與日期/);assert.ok(w.output.includes(data[0].sources[0].url));d.querySelector('#reset').click();d.querySelector('#download').click();assert.equal(JSON.parse(w.output).problems.length,100);
d.querySelector('[data-favorite="1"]').click();assert.equal(JSON.parse(w.localStorage.getItem('hundred-problems-favorites-v1'))[0],1);d.querySelector('#favoritesOnly').click();assert.equal(cards(),1);d.querySelector('[data-favorite="1"]').click();assert.equal(cards(),0);assert.equal(d.querySelector('#empty').hidden,false);d.querySelector('#emptyReset').click();
for(let i=1;i<=4;i++)d.querySelector(`[data-compare="${i}"]`).click();assert.equal(d.querySelector('#compareCount').textContent,'已選 3 / 3 項');d.querySelector('#showCompare').click();assert.equal(d.querySelectorAll('#compareGrid article').length,3);d.querySelector('#closeCompare').click();assert.equal(d.querySelector('#compareDialog').open,false);d.querySelector('#clearCompare').click();assert.equal(d.querySelector('#compareBar').hidden,true);
d.querySelector('[data-open="1"]').click();assert.equal(w.location.hash,'#problem-1');assert.equal(d.querySelector('#detail').open,true);assert.ok(d.querySelectorAll('#detail .sources a').length>0);d.querySelector('#closeDetail').click();await delay();assert.equal(d.querySelector('#detail').open,false);w.history.forward();await delay();assert.equal(d.querySelector('#detail').open,true);w.history.back();await delay();d.querySelector('[data-open="2"]').click();d.querySelector('#detail').dispatchEvent(new w.Event('cancel',{cancelable:true}));await delay();assert.equal(d.querySelector('#detail').open,false);d.querySelector('#methodBtn').click();assert.ok(d.querySelector('#methodDialog').open);d.querySelector('#closeMethod').click();assert.ok(!d.querySelector('#methodDialog').open);dom.window.close();
for(const stored of ['not-json','{}','[1,999,"2",null]']){dom=await setup({stored});assert.equal(dom.window.document.querySelectorAll('.card').length,100);if(stored.startsWith('['))assert.equal(dom.window.document.querySelector('#favCount').textContent,'1');dom.window.close();}dom=await setup({blocked:true});dom.window.document.querySelector('[data-favorite="1"]').click();assert.equal(dom.window.document.querySelector('#favCount').textContent,'1');assert.ok(!dom.window.document.querySelector('#storageNotice').hidden);dom.window.close();
dom=await setup({hash:'#problem-42'});assert.equal(dom.window.document.querySelector('#detail').open,true);dom.window.document.querySelector('#closeDetail').click();assert.equal(dom.window.location.hash,'');dom.window.close();dom=await setup({hash:'#problem-999'});assert.equal(dom.window.document.querySelector('#detail').open,false);dom.window.close();dom=await setup({fail:true});assert.equal(dom.window.document.querySelector('#download').disabled,true);dom.window.close();console.log('PASS: four filters, search, both sorts, reset/empty, JSON/CSV exports, favorites/persistence/invalid/blocked storage, compare limit/repeat/close, deep links/Back/Forward/Escape, invalid hash and fetch failure.');})().catch(e=>{console.error(e);process.exitCode=1});
